name: Code Quality

on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - "**"
      - "!main"

env:
  NODE_VERSION: "20.x"
  DB_USERNAME: postgres
  DB_PASSWORD: postgres
  DB_DATABASE: postgres
  DATABASE_URL: postgres://postgres:postgres@localhost:5432/postgres?schema=public

jobs:
  install:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
      - name: Get npm cache directory
        id: npm-cache-dir
        run: echo "dir=$(npm config get cache)" >> ${GITHUB_OUTPUT}
      - name: Cache npm
        uses: actions/cache@v4
        with:
          path: ${{ steps.npm-cache-dir.outputs.dir }}
          key: "${{ runner.os }}-npm-${{ hashFiles('package-lock.json') }}"
          restore-keys: |
            ${{ runner.os }}-npm-
      - name: Cache node modules
        uses: actions/cache@v4
        with:
          path: ./node_modules
          key: "${{ runner.os }}-node_modules-${{ hashFiles('package-lock.json') }}-${{ hashFiles('**/schema.prisma') }}"
          restore-keys: |
            ${{ runner.os }}-node_modules-
      - name: Cache e2e node modules
        uses: actions/cache@v4
        with:
          path: ./e2e/node_modules
          key: "${{ runner.os }}-node_modules_e2e-${{ hashFiles('./e2e/package-lock.json') }}"
          restore-keys: |
            ${{ runner.os }}-node_modules_e2e-
      - name: Install node dependencies
        run: npm ci
      - name: Generate prisma types
        run: npm run prisma -- generate
      - name: Install e2e node dependencies
        run: cd e2e && npm ci

  cypress:
    runs-on: ubuntu-latest
    needs:
      - install
    strategy:
      # https://github.com/cypress-io/github-action/issues/48
      fail-fast: false
      matrix:
        # Use 2 parallel instances
        containers: [1, 2]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
      - name: Restore cached node modules
        uses: actions/cache/restore@v4
        with:
          path: ./node_modules
          key: "${{ runner.os }}-node_modules-${{ hashFiles('package-lock.json') }}-${{ hashFiles('**/schema.prisma') }}"
      - name: Start services
        env:
          DB_USER: ${{ env.DB_USERNAME }}
          DB_PASSWORD: ${{ env.DB_PASSWORD }}
        run: |
          cd development
          chmod +x ./init/elasticsearch/init.sh
          sed -i 's/- \.\/volumes\/elasticsearch\/data:\/usr\/share\/elasticsearch\/data//g' ./docker-compose.yaml
          docker compose up -d db oidc elasticsearch
          sleep 120
          docker compose logs elasticsearch
      - name: Migrate database
        run: npm run prisma -- migrate deploy
      - name: Restore cached e2e node modules
        uses: actions/cache/restore@v4
        with:
          path: ./e2e/node_modules
          key: "${{ runner.os }}-node_modules_e2e-${{ hashFiles('./e2e/package-lock.json') }}"
      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          command: |
            npx cypress run \
              --browser edge \
              --record \
              --parallel \
              --key ${{ secrets.CYPRESS_RECORD_KEY }} \
              --ci-build-id ${{ github.repository }}-${{ github.head_ref || github.ref_name }}-${{ github.sha }}
          build: npm run build
          start: npm start
          wait-on: "http://localhost:4200"
          wait-on-timeout: 120
          working-directory: ./e2e
        env:
          VITE_APP_VERSION: 0.0.99+dev
          TZ: Europe/Zurich
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Stop services
        run: |
          cd development
          docker compose down
