name: Release Latest (temporary)

on:
  workflow_dispatch:

  pull_request:
    types: [ opened, synchronize, reopened ]
    branches:
      - 'release'

permissions: write-all

jobs:
  build_and_push_api:
    name: 'build and push api'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Create image
        uses: ./.github/actions/create-image
        with:
          IMAGE_NAME: ${{ vars.BASE_IMAGE_NAME }}-api
          TAG: latest
          VERSION: '1.3.0'
          DOCKERFILE: ./apps/server-asset-sg/docker/Dockerfile
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  build_and_push_app:
    name: 'build and push app'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Create image
        uses: ./.github/actions/create-image
        with:
          IMAGE_NAME: ${{ vars.BASE_IMAGE_NAME }}-app
          TAG: latest
          VERSION: '1.3.0'
          DOCKERFILE: ./apps/client-asset-sg/docker/Dockerfile
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  tag_commit:
    name: 'tag commit'
    needs:
      - build_and_push_api
      - build_and_push_app
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: tag latest
        uses: ./.github/actions/tag-commit
        with:
          TAG_NAME: latest
          SHA: ${{ github.sha }}
      - name: Tag version
        uses: ./.github/actions/tag-commit
        with:
          TAG_NAME: '1.3.0'
          SHA: ${{ github.sha }}

  create_release:
    name: 'create release'
    needs:
      - build_and_push_api
      - build_and_push_app
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Create release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: '1.3.0'
          name: 'swissgeol-assets v1.3.0'
          generate_release_notes: true
          make_latest: true
